# This file tells Render how to deploy your Python backend.
# It defines the services, build commands, and start commands.

services:
  # A Web Service for our Flask App
  - type: web
    name: pulsevest-engine
    env: python
    # Build steps
    buildCommand: "pip install -r requirements.txt"
    # How to start the server
    startCommand: "gunicorn --workers 4 --bind 0.0.0.0:$PORT app:app"
    # Environment variables
    envVars:
      - key: GOOGLE_API_KEY
        sync: false # This marks it as a secret to be set in the dashboard
      - key: PYTHON_VERSION
        value: 3.11.4 # Specify a recent, stable Python version
